version: "3.6"
networks:
  back:
services:
  client:
    image: vue-docker-nginx:latest
    # environment:
    #   API_URL: http://api.2mx.org/graphql
    ports:
      - 3000:80
    networks:
      - back
