version: "3.6"
networks:
  back:
services:
  local:
    image: vue-docker-nginx:latest
    ports:
      - 3000:80
    networks:
      - back
  client:
    image: ghcr.io/gromov-io/vue-docker-nginx:latest
    ports:
      - 3001:80
    networks:
      - back
